# Generated by Django 3.2.8 on 2021-10-12 15:41

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descripton', models.TextField()),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=product.models.productImage)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
